//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sudoku.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sudoku.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        public static string ButtonDifficultyEasy {
            get {
                return ResourceManager.GetString("ButtonDifficultyEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        public static string ButtonDifficultyHard {
            get {
                return ResourceManager.GetString("ButtonDifficultyHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string ButtonDifficultyMedium {
            get {
                return ResourceManager.GetString("ButtonDifficultyMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Game.
        /// </summary>
        public static string ButtonNewGame {
            get {
                return ResourceManager.GetString("ButtonNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string ButtonValidate {
            get {
                return ResourceManager.GetString("ButtonValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place a marker.
        /// </summary>
        public static string LabelOverlayChooseMarker {
            get {
                return ResourceManager.GetString("LabelOverlayChooseMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place a number.
        /// </summary>
        public static string LabelOverlayChooseNumber {
            get {
                return ResourceManager.GetString("LabelOverlayChooseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string LabelOverlaySingleSolutionWait {
            get {
                return ResourceManager.GetString("LabelOverlaySingleSolutionWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a marker:.
        /// </summary>
        public static string LabelSelectMarker {
            get {
                return ResourceManager.GetString("LabelSelectMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a number:.
        /// </summary>
        public static string LabelSelectNumber {
            get {
                return ResourceManager.GetString("LabelSelectNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicts found!.
        /// </summary>
        public static string LabelValidateConflicts {
            get {
                return ResourceManager.GetString("LabelValidateConflicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No conflicts found.
        /// </summary>
        public static string LabelValidateNoConflicts {
            get {
                return ResourceManager.GetString("LabelValidateNoConflicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set all markers automatically.
        /// </summary>
        public static string MenuFillAllMarkers {
            get {
                return ResourceManager.GetString("MenuFillAllMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string MenuGame {
            get {
                return ResourceManager.GetString("MenuGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty playing field.
        /// </summary>
        public static string MenuGameEmptySudoku {
            get {
                return ResourceManager.GetString("MenuGameEmptySudoku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New game....
        /// </summary>
        public static string MenuGameNewGame {
            get {
                return ResourceManager.GetString("MenuGameNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Sudoku.
        /// </summary>
        public static string MenuGamePrint {
            get {
                return ResourceManager.GetString("MenuGamePrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit program.
        /// </summary>
        public static string MenuGameQuitProgram {
            get {
                return ResourceManager.GetString("MenuGameQuitProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Slots.
        /// </summary>
        public static string MenuGameSaveSlots {
            get {
                return ResourceManager.GetString("MenuGameSaveSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all slots.
        /// </summary>
        public static string MenuGameSaveSlotsDeleteAll {
            get {
                return ResourceManager.GetString("MenuGameSaveSlotsDeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot 1: Load.
        /// </summary>
        public static string MenuGameSaveSlotsLoadFromSlot1 {
            get {
                return ResourceManager.GetString("MenuGameSaveSlotsLoadFromSlot1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot 2: Load.
        /// </summary>
        public static string MenuGameSaveSlotsLoadFromSlot2 {
            get {
                return ResourceManager.GetString("MenuGameSaveSlotsLoadFromSlot2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot 3: Load.
        /// </summary>
        public static string MenuGameSaveSlotsLoadFromSlot3 {
            get {
                return ResourceManager.GetString("MenuGameSaveSlotsLoadFromSlot3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot 4: Load.
        /// </summary>
        public static string MenuGameSaveSlotsLoadFromSlot4 {
            get {
                return ResourceManager.GetString("MenuGameSaveSlotsLoadFromSlot4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot 5: Load.
        /// </summary>
        public static string MenuGameSaveSlotsLoadFromSlot5 {
            get {
                return ResourceManager.GetString("MenuGameSaveSlotsLoadFromSlot5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot 1: Save.
        /// </summary>
        public static string MenuGameSaveSlotsSaveToSlot1 {
            get {
                return ResourceManager.GetString("MenuGameSaveSlotsSaveToSlot1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot 2: Save.
        /// </summary>
        public static string MenuGameSaveSlotsSaveToSlot2 {
            get {
                return ResourceManager.GetString("MenuGameSaveSlotsSaveToSlot2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot 3: Save.
        /// </summary>
        public static string MenuGameSaveSlotsSaveToSlot3 {
            get {
                return ResourceManager.GetString("MenuGameSaveSlotsSaveToSlot3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot 4: Save.
        /// </summary>
        public static string MenuGameSaveSlotsSaveToSlot4 {
            get {
                return ResourceManager.GetString("MenuGameSaveSlotsSaveToSlot4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot 5: Save.
        /// </summary>
        public static string MenuGameSaveSlotsSaveToSlot5 {
            get {
                return ResourceManager.GetString("MenuGameSaveSlotsSaveToSlot5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MenuGameSettings {
            get {
                return ResourceManager.GetString("MenuGameSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Sudokus with a single solution.
        /// </summary>
        public static string MenuGameSettingsSingleSolution {
            get {
                return ResourceManager.GetString("MenuGameSettingsSingleSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solve this Sudoku.
        /// </summary>
        public static string MenuGameSolveSudoku {
            get {
                return ResourceManager.GetString("MenuGameSolveSudoku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuHelpAbout {
            get {
                return ResourceManager.GetString("MenuHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soduku rules.
        /// </summary>
        public static string MenuHelpRules {
            get {
                return ResourceManager.GetString("MenuHelpRules", resourceCulture);
            }
        }
    }
}
